### ISSUE TITLE
Does this plugin support windows platform?

### ISSUE THREAD

**Issue by XingweiLin** [alexhude/LoadProcConfig#2]
Hi Alexander,
Does this plugin support windows platform?
I copied those two files into `plugins` folder.
But it didn't show ` Load Processor Config` option in `Edit\plugin`

**Comment by alexhude** [comment]
Currently for IDA 7.0 Win you have to build it yourself. For IDA 6.95 Win you can use 
**LoadProcConfig.p64** and **LoadProcConfig.plw**.

**Comment by XingweiLin** [comment]
Is there a tutorial that can guide me to build?

**Comment by alexhude** [comment]
No, but there is a Visual Studio project - **LoadProcConfig.vcxproj**
